<?php
defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_aurahr_academia_create_assessment' => [
        'classname'    => 'local_aurahr_academia\external\create_assessment',
        'description'  => 'Create an academia round assessment for a job',
        'type'         => 'write',
        'ajax'         => true,
        'capabilities' => 'local/aurahr_academia:manage',
    ],
    'local_aurahr_academia_generate_questions' => [
        'classname'    => 'local_aurahr_academia\external\generate_questions',
        'description'  => 'Generate quiz questions using AI and import into Moodle',
        'type'         => 'write',
        'ajax'         => true,
        'capabilities' => 'local/aurahr_academia:manage',
    ],
    'local_aurahr_academia_schedule_test' => [
        'classname'    => 'local_aurahr_academia\external\schedule_test',
        'description'  => 'Schedule a test window and enroll candidates',
        'type'         => 'write',
        'ajax'         => true,
        'capabilities' => 'local/aurahr_academia:manage',
    ],
    'local_aurahr_academia_get_assessment' => [
        'classname'    => 'local_aurahr_academia\external\get_assessment',
        'description'  => 'Get assessment details including enrolled candidates',
        'type'         => 'read',
        'ajax'         => true,
    ],
    'local_aurahr_academia_get_results' => [
        'classname'    => 'local_aurahr_academia\external\get_results',
        'description'  => 'Fetch results from gradebook and update pipeline',
        'type'         => 'write',
        'ajax'         => true,
        'capabilities' => 'local/aurahr_academia:viewresults',
    ],
    'local_aurahr_academia_get_candidate_test' => [
        'classname'    => 'local_aurahr_academia\external\get_candidate_test',
        'description'  => 'Get test info for the current candidate',
        'type'         => 'read',
        'ajax'         => true,
        'capabilities' => 'local/aurahr_academia:take',
    ],
    'local_aurahr_academia_submit_test' => [
        'classname'    => 'local_aurahr_academia\external\submit_test',
        'description'  => 'Submit an academia test score',
        'type'         => 'write',
        'ajax'         => true,
    ],
    'local_aurahr_academia_log_event' => [
        'classname'    => 'local_aurahr_academia\external\log_event',
        'description'  => 'Log a proctoring violation event',
        'type'         => 'write',
        'ajax'         => true,
    ],
    'local_aurahr_academia_finalize_assessment' => [
        'classname'    => 'local_aurahr_academia\external\finalize_assessment',
        'description'  => 'Finalize assessment round, promote top N candidates to interview and reject the rest',
        'type'         => 'write',
        'ajax'         => true,
        'capabilities' => 'local/aurahr_academia:manage',
    ],
];

$all_functions = [
    'core_webservice_get_site_info',
    'local_aurahr_academia_create_assessment',
    'local_aurahr_academia_finalize_assessment',
    'local_aurahr_academia_generate_questions',
    'local_aurahr_academia_get_assessment',
    'local_aurahr_academia_get_candidate_test',
    'local_aurahr_academia_get_results',
    'local_aurahr_academia_log_event',
    'local_aurahr_academia_schedule_test',
    'local_aurahr_academia_submit_test',
    'local_aurahr_interview_ai_evaluate',
    'local_aurahr_interview_finalise',
    'local_aurahr_interview_get_details',
    'local_aurahr_interview_list',
    'local_aurahr_interview_schedule',
    'local_aurahr_interview_submit_score',
    'local_aurahr_jdparser_get_analysis',
    'local_aurahr_jdparser_match_candidates',
    'local_aurahr_jdparser_parse',
    'local_aurahr_jdparser_update_config',
    'local_aurahr_jobs_analyze_socials',
    'local_aurahr_jobs_apply',
    'local_aurahr_jobs_change_password',
    'local_aurahr_jobs_create_job',
    'local_aurahr_jobs_delete_account',
    'local_aurahr_jobs_delete_job',
    'local_aurahr_jobs_finalize_jd',
    'local_aurahr_jobs_get_application',
    'local_aurahr_jobs_get_job',
    'local_aurahr_jobs_get_notifications',
    'local_aurahr_jobs_get_org_config',
    'local_aurahr_jobs_get_photo',
    'local_aurahr_jobs_get_stats',
    'local_aurahr_jobs_get_user_prefs',
    'local_aurahr_jobs_list_applications',
    'local_aurahr_jobs_list_jobs',
    'local_aurahr_jobs_update_candidate_urls',
    'local_aurahr_jobs_update_job',
    'local_aurahr_jobs_update_org_config',
    'local_aurahr_jobs_update_stage',
    'local_aurahr_jobs_update_user_prefs',
    'local_aurahr_jobs_upload_photo',
    'local_aurahr_jobs_upload_resume',
    'local_aurahr_proctor_get_report',
    'local_aurahr_proctor_log_event',
    'local_aurahr_scheduler_approve_reschedule',
    'local_aurahr_scheduler_auto_schedule',
    'local_aurahr_scheduler_block_time',
    'local_aurahr_scheduler_cancel_interview',
    'local_aurahr_scheduler_delete_blocked_time',
    'local_aurahr_scheduler_get_availability',
    'local_aurahr_scheduler_get_blocked_times',
    'local_aurahr_scheduler_get_calendar',
    'local_aurahr_scheduler_get_pending_requests',
    'local_aurahr_scheduler_get_rules',
    'local_aurahr_scheduler_override_slot',
    'local_aurahr_scheduler_request_reschedule',
    'local_aurahr_scheduler_set_availability',
    'local_aurahr_scheduler_update_rules'
];

$services = [
    'AuraHR Academia API' => [
        'functions'       => $all_functions,
        'restrictedusers' => 0,
        'enabled'         => 1,
        'shortname'       => 'aurahr_academia',
    ],
    'AuraHR Jobs API' => [
        'functions'       => $all_functions,
        'restrictedusers' => 0,
        'enabled'         => 1,
        'shortname'       => 'aurahr_jobs',
    ],
    'AuraHR User API' => [
        'functions'       => $all_functions,
        'restrictedusers' => 0,
        'enabled'         => 1,
        'shortname'       => 'aurahr_user',
    ],
];
