import { NextResponse } from 'next/server';
import { getDb, saveDb } from '@/lib/db';

export async function POST() {
  const db = await getDb();

  db.employees = [
    { id: '1', name: 'Sarah Chen', email: 'sarah@nexushr.com', role: 'Engineering Director', location: 'San Francisco, CA', salary: 4200000, state: 'Maharashtra', taxRegime: 'new', pan: 'ABCPS1234A', uan: '100208765432' },
    { id: '2', name: 'Rahul Verma', email: 'rahul@nexushr.com', role: 'Product Manager', location: 'Bengaluru, KA', salary: 2800000, state: 'Karnataka', taxRegime: 'new', pan: 'AABPV4321B', uan: '100298765001' },
    { id: '3', name: 'Anita Desai', email: 'anita@nexushr.com', role: 'HR Business Partner', location: 'Mumbai, MH', salary: 1800000, state: 'Maharashtra', taxRegime: 'old', pan: 'AAAPD5678C', uan: '100312345009' },
    { id: '4', name: 'David Kim', email: 'david@nexushr.com', role: 'Backend Engineer', location: 'Hyderabad, TS', salary: 2200000, state: 'Maharashtra', taxRegime: 'new', pan: 'ABCDK8765D', uan: '100412345678' },
    { id: '5', name: 'Sandeep Varma', email: 'sandeep.varma@nexushr.com', role: 'Senior VLSI Engineer', location: 'Bengaluru, KA', salary: 3600000, state: 'Karnataka', taxRegime: 'new', pan: 'AADSV9012E', uan: '100512349876' },
    { id: '6', name: 'Megha Iyer', email: 'megha.iyer@nexushr.com', role: 'HR Compliance Specialist', location: 'Chennai, TN', salary: 1600000, state: 'Tamil Nadu', taxRegime: 'old', pan: 'AAFMI6543F', uan: '100612348765' },
    { id: '7', name: 'Karan Bir Singh', email: 'karan.singh@nexushr.com', role: 'Digital Logic Designer', location: 'Chandigarh, PB', salary: 1400000, state: 'Maharashtra', taxRegime: 'new', pan: 'AAGKS2109G', uan: '100712347654' },
    { id: '8', name: 'Tanvi Gupta', email: 'tanvi.gupta@nexushr.com', role: 'Systems Analyst', location: 'New Delhi, DL', salary: 2100000, state: 'Maharashtra', taxRegime: 'old', pan: 'AAHGT7654H', uan: '100812346543' },
    { id: '9', name: 'Amitabh Das', email: 'amitabh.das@nexushr.com', role: 'Project Lead — Infrastructure', location: 'Hyderabad, TS', salary: 4500000, state: 'Maharashtra', taxRegime: 'new', pan: 'AAIAD3210I', uan: '100912345432' }
  ];

  db.activities = [
    { id: 'a1', employeeId: '1', action: 'Approved Q1 Bonus Release', status: 'Done', time: '2h ago' },
    { id: 'a2', employeeId: '2', action: 'Requested Equipment Upgrade', status: 'Pending', time: '4h ago' },
    { id: 'a3', employeeId: '3', action: 'Labour Law Update — Maharashtra', status: 'Alert', time: '12h ago' },
    { id: 'a4', employeeId: '4', action: 'Onboarding Sequence Complete', status: 'Done', time: '1d ago' }
  ];

  // 10 Indian candidates
  db.candidates = [
    { id: 'c1', name: 'Arjun Mehta', role: 'Senior Frontend Engineer', status: 'Offer', matchPercent: 97, matchTags: ['React', 'TypeScript', 'System Design'], phone: '+91-98201-34567', education: 'B.Tech Computer Science', institute: 'IIT Bombay', aiInterviewScore: 92, salaryExpectation: 2800000, source: 'LinkedIn', gender: 'Male', score: { technical: 95, culture: 88, communication: 92, leadership: 85, adaptability: 90 }, interviewLogs: [], assessments: [] },
    { id: 'c2', name: 'Priya Sharma', role: 'Product Designer', status: 'Interview', matchPercent: 93, matchTags: ['Figma', 'UX Research', 'Prototyping'], phone: '+91-99103-56789', education: 'B.Des', institute: 'NID Ahmedabad', aiInterviewScore: 88, salaryExpectation: 1800000, source: 'Naukri', gender: 'Female', score: { technical: 88, culture: 96, communication: 94, leadership: 80, adaptability: 91 }, interviewLogs: [], assessments: [] },
    { id: 'c3', name: 'Ishaan Nair', role: 'Full Stack Developer', status: 'Interview', matchPercent: 89, matchTags: ['Node.js', 'React', 'PostgreSQL'], phone: '+91-97034-87654', education: 'B.Tech IT', institute: 'NIT Trichy', aiInterviewScore: 85, salaryExpectation: 2200000, source: 'Referral', gender: 'Male', score: { technical: 90, culture: 85, communication: 88, leadership: 78, adaptability: 87 }, interviewLogs: [], assessments: [] },
    { id: 'c4', name: 'Lakshmi Iyer', role: 'Data Scientist', status: 'Screened', matchPercent: 86, matchTags: ['Python', 'ML', 'TensorFlow'], phone: '+91-98765-43210', education: 'M.Tech AI', institute: 'IIT Madras', aiInterviewScore: 82, salaryExpectation: 2600000, source: 'LinkedIn', gender: 'Female', score: { technical: 93, culture: 82, communication: 80, leadership: 76, adaptability: 85 }, interviewLogs: [], assessments: [] },
    { id: 'c5', name: 'Vikram Bose', role: 'DevOps Engineer', status: 'Applied', matchPercent: 81, matchTags: ['AWS', 'Kubernetes', 'Docker'], phone: '+91-96321-78901', education: 'B.E. Electronics', institute: 'BITS Pilani', aiInterviewScore: 78, salaryExpectation: 2400000, source: 'GitHub', gender: 'Male', score: { technical: 87, culture: 80, communication: 82, leadership: 70, adaptability: 88 }, interviewLogs: [], assessments: [] },
    { id: 'c6', name: 'Sneha Kulkarni', role: 'Backend Engineer', status: 'Screened', matchPercent: 84, matchTags: ['Java', 'Spring Boot', 'MySQL'], phone: '+91-98450-23456', education: 'B.E. CS', institute: 'VIT Vellore', aiInterviewScore: 80, salaryExpectation: 1900000, source: 'Internshala', gender: 'Female', score: { technical: 86, culture: 88, communication: 84, leadership: 72, adaptability: 82 }, interviewLogs: [], assessments: [] },
    { id: 'c7', name: 'Rohan Gupta', role: 'iOS Developer', status: 'Applied', matchPercent: 78, matchTags: ['Swift', 'XCode', 'CoreData'], phone: '+91-91023-65432', education: 'BCA', institute: 'Delhi University', aiInterviewScore: 74, salaryExpectation: 1700000, source: 'Naukri', gender: 'Male', score: { technical: 80, culture: 84, communication: 78, leadership: 65, adaptability: 80 }, interviewLogs: [], assessments: [] },
    { id: 'c8', name: 'Meera Pillai', role: 'Cloud Architect', status: 'Interview', matchPercent: 91, matchTags: ['GCP', 'Terraform', 'Microservices'], phone: '+91-98900-12345', education: 'M.Tech Cloud', institute: 'IIT Delhi', aiInterviewScore: 89, salaryExpectation: 3200000, source: 'LinkedIn', gender: 'Female', score: { technical: 94, culture: 86, communication: 90, leadership: 85, adaptability: 92 }, interviewLogs: [], assessments: [] },
    { id: 'c9', name: 'Aditya Singh', role: 'ML Engineer', status: 'Offer', matchPercent: 95, matchTags: ['PyTorch', 'LLMs', 'MLOps'], phone: '+91-99871-54321', education: 'M.Tech AI/ML', institute: 'IISc Bangalore', aiInterviewScore: 94, salaryExpectation: 3500000, source: 'Referral', gender: 'Male', score: { technical: 97, culture: 84, communication: 88, leadership: 82, adaptability: 93 }, interviewLogs: [], assessments: [] },
    { id: 'c10', name: 'Divya Krishnan', role: 'HR Tech Specialist', status: 'Applied', matchPercent: 76, matchTags: ['HRMS', 'Compliance', 'Zoho People'], phone: '+91-97654-32109', education: 'MBA HR', institute: 'XLRI Jamshedpur', aiInterviewScore: 72, salaryExpectation: 1500000, source: 'Naukri', gender: 'Female', score: { technical: 74, culture: 92, communication: 90, leadership: 78, adaptability: 85 }, interviewLogs: [], assessments: [] },
    { id: 'c11', name: 'Suresh Raina', role: 'VLSI Design Engineer', status: 'Screened', matchPercent: 88, matchTags: ['VLSI', 'SystemVerilog', 'FPGA', 'Cadence'], phone: '+91-98102-45678', education: 'M.Tech VLSI', institute: 'IIT Kharagpur', aiInterviewScore: 84, salaryExpectation: 2900000, source: 'LinkedIn', gender: 'Male', score: { technical: 91, culture: 82, communication: 80, leadership: 74, adaptability: 86 }, interviewLogs: [], assessments: [] },
    { id: 'c12', name: 'Meenakshi Sundaram', role: 'AI Research Engineer', status: 'Interview', matchPercent: 94, matchTags: ['PyTorch', 'NLP', 'LLMs', 'Python'], phone: '+91-99045-23456', education: 'M.Tech AI', institute: 'IIT Madras', aiInterviewScore: 91, salaryExpectation: 3800000, source: 'Referral', gender: 'Female', score: { technical: 95, culture: 88, communication: 86, leadership: 80, adaptability: 92 }, interviewLogs: [], assessments: [] },
    { id: 'c13', name: 'Kabir Khan', role: 'Full Stack Engineer', status: 'Applied', matchPercent: 83, matchTags: ['React', 'Node.js', 'MongoDB', 'Redux'], phone: '+91-97890-34567', education: 'B.Tech CS', institute: 'NIT Surathkal', aiInterviewScore: 79, salaryExpectation: 2100000, source: 'GitHub', gender: 'Male', score: { technical: 85, culture: 84, communication: 82, leadership: 68, adaptability: 83 }, interviewLogs: [], assessments: [] },
    { id: 'c14', name: 'Nalini Venkataraman', role: 'VLSI Verification Engineer', status: 'Screened', matchPercent: 85, matchTags: ['UVM', 'SystemVerilog', 'Synopsys', 'DFT'], phone: '+91-98234-56789', education: 'B.E. Electronics', institute: 'BITS Pilani', aiInterviewScore: 81, salaryExpectation: 2500000, source: 'Naukri', gender: 'Female', score: { technical: 88, culture: 86, communication: 84, leadership: 72, adaptability: 87 }, interviewLogs: [], assessments: [] },
    { id: 'c15', name: 'Rahul Tripathi', role: 'MLOps Engineer', status: 'Applied', matchPercent: 80, matchTags: ['MLOps', 'Kubeflow', 'Python', 'GCP'], phone: '+91-96543-21098', education: 'M.Sc. Data Science', institute: 'IISc Bangalore', aiInterviewScore: 77, salaryExpectation: 3100000, source: 'LinkedIn', gender: 'Male', score: { technical: 83, culture: 80, communication: 78, leadership: 70, adaptability: 84 }, interviewLogs: [], assessments: [] },
    { id: 'c16', name: 'Aditi Rao', role: 'Embedded Systems Engineer', status: 'Applied', matchPercent: 82, matchTags: ['Embedded C', 'RTOS', 'STM32', 'Arduino', 'C++'], phone: '+91-98701-23456', education: 'B.Tech ECE', institute: 'NIT Warangal', aiInterviewScore: 78, salaryExpectation: 1800000, source: 'Naukri', gender: 'Female', score: { technical: 85, culture: 83, communication: 79, leadership: 68, adaptability: 82 }, interviewLogs: [], assessments: [] },
    { id: 'c17', name: 'Vikram Seth', role: 'Full Stack Engineer', status: 'Screened', matchPercent: 86, matchTags: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker'], phone: '+91-99123-45678', education: 'B.Tech CS', institute: 'BITS Pilani', aiInterviewScore: 83, salaryExpectation: 2800000, source: 'LinkedIn', gender: 'Male', score: { technical: 88, culture: 85, communication: 84, leadership: 76, adaptability: 86 }, interviewLogs: [], assessments: [] },
    { id: 'c18', name: 'Rahul Dravid', role: 'Compliance Officer', status: 'Applied', matchPercent: 71, matchTags: ['Labour Law', 'EPF', 'ESI', 'Statutory Compliance', 'HRMS'], phone: '+91-98456-78901', education: 'LLB', institute: 'National Law School Bangalore', aiInterviewScore: 69, salaryExpectation: 2200000, source: 'Naukri', gender: 'Male', score: { technical: 68, culture: 92, communication: 90, leadership: 80, adaptability: 78 }, interviewLogs: [], assessments: [] },
    { id: 'c19', name: 'Sneha Kapoor', role: 'AI Researcher', status: 'Interview', matchPercent: 91, matchTags: ['Python', 'PyTorch', 'NLP', 'Transformers', 'LLMs'], phone: '+91-98234-09876', education: 'M.Tech AI', institute: 'IIT Delhi', aiInterviewScore: 88, salaryExpectation: 3400000, source: 'Referral', gender: 'Female', score: { technical: 93, culture: 87, communication: 85, leadership: 79, adaptability: 90 }, interviewLogs: [], assessments: [] },
    { id: 'c20', name: 'Zoya Akhtar', role: 'VLSI Engineer', status: 'Screened', matchPercent: 87, matchTags: ['VLSI', 'Verilog', 'Cadence', 'UVM', 'ASIC'], phone: '+91-97654-09876', education: 'M.Tech VLSI', institute: 'NIT Calicut', aiInterviewScore: 82, salaryExpectation: 2600000, source: 'LinkedIn', gender: 'Female', score: { technical: 89, culture: 84, communication: 82, leadership: 71, adaptability: 85 }, interviewLogs: [], assessments: [] },
    { id: 'c21', name: 'Rohan Iyer', role: 'VLSI / RTL Design Engineer', status: 'Applied', matchPercent: 90, matchTags: ['VLSI', 'Verilog', 'SystemVerilog', 'FPGA', 'UVM', 'Synopsys'], phone: '+91-98012-34567', education: 'M.Tech VLSI', institute: 'IIT Madras', aiInterviewScore: 86, salaryExpectation: 2700000, source: 'Naukri', gender: 'Male', score: { technical: 92, culture: 83, communication: 81, leadership: 73, adaptability: 84 }, interviewLogs: [], assessments: [] },
    { id: 'c22', name: 'Ananya Nair', role: 'AI / ML Engineer', status: 'Screened', matchPercent: 93, matchTags: ['Python', 'PyTorch', 'Machine Learning', 'NLP', 'TensorFlow', 'Scikit-learn'], phone: '+91-97890-12345', education: 'M.Tech AI', institute: 'IIT Bombay', aiInterviewScore: 90, salaryExpectation: 3600000, source: 'Referral', gender: 'Female', score: { technical: 94, culture: 88, communication: 87, leadership: 80, adaptability: 91 }, interviewLogs: [], assessments: [] },
    { id: 'c23', name: 'Priya Sharma', role: 'Full Stack / React Developer', status: 'Applied', matchPercent: 85, matchTags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Docker'], phone: '+91-99012-98765', education: 'B.Tech CS', institute: 'NIT Delhi', aiInterviewScore: 80, salaryExpectation: 2400000, source: 'LinkedIn', gender: 'Female', score: { technical: 86, culture: 85, communication: 84, leadership: 72, adaptability: 83 }, interviewLogs: [], assessments: [] },
    { id: 'c24', name: 'Arjun Mehta', role: 'Backend Engineer', status: 'Interview', matchPercent: 88, matchTags: ['Node.js', 'Python', 'GraphQL', 'AWS', 'Microservices', 'Kafka'], phone: '+91-98901-23456', education: 'B.Tech CS', institute: 'IIT Hyderabad', aiInterviewScore: 85, salaryExpectation: 3000000, source: 'Referral', gender: 'Male', score: { technical: 90, culture: 86, communication: 83, leadership: 77, adaptability: 87 }, interviewLogs: [], assessments: [] },
    { id: 'c25', name: 'Dev Patel', role: 'DevOps / Cloud Engineer', status: 'Applied', matchPercent: 84, matchTags: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Linux'], phone: '+91-97012-34567', education: 'B.Tech IT', institute: 'BITS Pilani', aiInterviewScore: 79, salaryExpectation: 2700000, source: 'GitHub', gender: 'Male', score: { technical: 87, culture: 82, communication: 80, leadership: 70, adaptability: 86 }, interviewLogs: [], assessments: [] },
    { id: 'c26', name: 'Nikhil Kamath', role: 'Digital Design Engineer', status: 'Applied', matchPercent: 88, matchTags: ['VLSI', 'Verilog', 'SystemVerilog', 'Digital Design', 'FPGA', 'Cadence', 'RTL'], phone: '+91-98765-11223', education: 'M.Tech VLSI Design', institute: 'IIT Bangalore', aiInterviewScore: 84, salaryExpectation: 2850000, source: 'LinkedIn', gender: 'Male', score: { technical: 91, culture: 82, communication: 80, leadership: 72, adaptability: 85 }, interviewLogs: [], assessments: [] },
    { id: 'c27', name: 'Sanya Malhotra', role: 'VLSI Verification Engineer', status: 'Applied', matchPercent: 83, matchTags: ['Verification', 'UVM', 'SystemVerilog', 'Synopsys', 'ModelSim', 'DFT', 'STA'], phone: '+91-97890-44556', education: 'B.Tech ECE', institute: 'NIT Warangal', aiInterviewScore: 79, salaryExpectation: 1950000, source: 'Naukri', gender: 'Female', score: { technical: 87, culture: 85, communication: 83, leadership: 68, adaptability: 84 }, interviewLogs: [], assessments: [] },
    { id: 'c28', name: 'Ritesh Agarwal', role: 'Analog Layout Engineer', status: 'Applied', matchPercent: 85, matchTags: ['Analog Design', 'Analog Layout', 'Cadence', 'Spectre', 'Calibre', 'VLSI', 'Physical Design'], phone: '+91-96012-77889', education: 'M.Tech Microelectronics', institute: 'IIT Delhi', aiInterviewScore: 81, salaryExpectation: 3200000, source: 'Referral', gender: 'Male', score: { technical: 89, culture: 81, communication: 78, leadership: 74, adaptability: 83 }, interviewLogs: [], assessments: [] }
  ];

  db.jobDescriptions = [
    {
      id: 'jd1', title: 'Senior Full Stack Engineer', department: 'Engineering',
      salaryBudget: 2800000, active: true, createdAt: new Date().toISOString(),
      mustHave: ['React', 'Node.js', 'TypeScript', '4+ years experience', 'System Design'],
      niceToHave: ['GraphQL', 'AWS', 'Docker', 'Open Source contributions']
    },
    {
      id: 'jd2', title: 'Data Scientist / ML Engineer', department: 'AI Research',
      salaryBudget: 3200000, active: true, createdAt: new Date().toISOString(),
      mustHave: ['Python', 'Machine Learning', 'TensorFlow or PyTorch', 'Statistics'],
      niceToHave: ['LLM Fine-tuning', 'MLOps', 'Spark', 'Kaggle presence']
    }
  ];

  await saveDb(db);
  return NextResponse.json({ message: 'Seeded 10 Indian profiles and JDs successfully' });
}
