

/* ---------- CHUNK ---------- */

"                  {activeTab === 'jd' && (\n                    <div className=\"space-y-6\">\n                      <div className=\"bento-card p-6\">\n                        <h3 className=\"font-serif text-lg font-semibold text-ink mb-4\">JD Parser Match</h3>\n                        <div className=\"flex items-center gap-6 mb-6\">\n                          <div className=\"relative w-24 h-24 shrink-0 flex items-center justify-center rounded-full border-4 border-emerald-500 text-2xl font-serif font-bold text-emerald-600\">\n                            {selectedApp.jd_score || 0}%\n                          </div>\n                          <div>\n                            <p className=\"text-sm text-ink/60\">Your resume matched highly with the core requirements.</p>\n                            {selectedApp.jd_score >= 50 && (\n                              <p className=\"text-sm font-semibold text-emerald-600 mt-1 flex items-center gap-1\"><Check size={16} /> Shortlisted for next round</p>\n                            )}\n                          </div>\n                        </div>\n                        <div className=\"grid grid-cols-2 gap-4\">\n                          <div className=\"p-4 bg-emerald-500/5 rounded-xl border border-emerald-500/10\">\n                            <p className=\"text-xs text-ink/40 font-semibold uppercase mb-2\">Matched Skills</p>\n                            <div className=\"flex flex-wrap gap-2\">\n                              {(() => {\n                                try {\n                                  const skills = JSON.parse(selectedApp.matched_skills || '[]');\n                                  if (!skills.length) return <span className=\"text-xs text-ink/40\">None extracted</span>;\n                                  return skills.map((s: string, i: number) => (\n                                    <span key={i} className=\"text-xs px-2 py-1 bg-white rounded-md shadow-sm text-ink\">{s}</span>\n                                  ));\n                    
<truncated 7811 bytes>

/* ---------- CHUNK ---------- */

"interface Application {\n  id: number;\n  jobid: number;\n  job_title: string;\n  job_department: string;\n  stage: string;\n  jd_score: number;\n  academia_score: number;\n  interview_score: number;\n  overall_score: number;\n  malpractice: number;\n  matched_skills: string;\n  resume_skills: string;\n  timecreated: number;\n}\n\nconst stageConfig: Record<string, { label: string; icon: React.ReactNode; color: string }> = {\n  applied:   { label: 'Applied',          icon: <Clock size={14} />,        color: 'bg-blue-500/15 text-blue-700 border-blue-200' },\n  screened:  { label: 'Under Review',     icon: <FileText size={14} />,     color: 'bg-amber-500/15 text-amber-700 border-amber-200' },\n  academia:  { label: 'Assessment',       icon: <FileText size={14} />,     color: 'bg-purple-500/15 text-purple-700 border-purple-200' },\n  interview: { label: 'Interview',        icon: <Briefcase size={14} />,   color: 'bg-gold/15 text-gold border-gold/30' },\n  offer:     { label: 'Offer',            icon: <CheckCircle size={14} />, color: 'bg-sage/15 text-sage border-sage/30' },\n  selected:  { label: 'Selected',         icon: <CheckCircle size={14} />, color: 'bg-emerald-500/15 text-emerald-700 border-emerald-200' },\n  rejected:  { label: 'Rejected',         icon: <XCircle size={14} />,     color: 'bg-rust/15 text-rust border-rust/30' },\n};\n\nexport default function MyApplicationsPage() {\n  const [applications, setApplications] = useState<Application[]>([]);\n  const [loading, setLoading] = useState(true);\n  const [selectedAppId, setSelectedAppId] = useState<number | null>(null);\n  const [activeTab, setActiveTab] = useState<'jd' | 'academia' | 'interview' | 'result'>('jd');\n  const [assessmentData, setAssessmentData] = useState<any>(null);\n  const [interviewData, setInterviewData] = useState<any>(null);\n\n  useEffect(() => {\n    async function load() {\n      try {\n        const res = await moodleCall<{ applications: Application[] }>(\n          'local_aurahr_jobs_list_applications',\n          { jobid: 0 }\n
<truncated 1133 bytes>

/* ---------- CHUNK ---------- */

"  useEffect(() => {\n    const selectedApp = applications.find(a => a.id === selectedAppId);\n    if (!selectedApp) return;\n\n    if (activeTab === 'academia') {\n      moodleCall<any>('local_aurahr_jobs_get_assessment', { jobid: selectedApp.jobid })\n        .then(res => setAssessmentData(res.found ? res : null))\n        .catch(console.error);\n    } else if (activeTab === 'interview') {\n      moodleCall<any[]>('local_aurahr_scheduler_get_interviews')\n        .then(res => {\n          const match = (res || []).find(i => i.applicationid === selectedApp.id);\n          setInterviewData(match || null);\n        })\n        .catch(console.error);\n    }\n  }, [selectedAppId, activeTab, applications]);\n\n  useEffect(() => {\n    // Reset data when app changes\n    setAssessmentData(null);\n    setInterviewData(null);\n  }, [selectedAppId]);"

/* ---------- CHUNK ---------- */

"      {/* Grid for other widgets */}\n      <motion.div {...fadeUp} transition={{ delay: 0.3 }} className=\"grid grid-cols-1 md:grid-cols-2 gap-6\">\n        {/* Tests Scheduled Widget */}\n        <div className=\"bento-card p-6\">\n          <h2 className=\"font-serif text-lg font-semibold text-ink flex items-center gap-2 mb-4\">\n            <Activity size={18} className=\"text-purple-500\" />\n            Tests Scheduled\n          </h2>\n          <div className=\"space-y-3\">\n            {Object.keys(assessments).length === 0 ? (\n              <p className=\"text-xs text-ink/40 italic\">No tests scheduled at the moment.</p>\n            ) : (\n              Object.values(assessments).map((assessment: any) => {\n                if (!assessment || assessment.status === 'none') return null;\n                const isLive = assessment.status === 'active';\n                return (\n                  <div key={assessment.id} className=\"p-4 rounded-xl bg-purple-500/5 border border-purple-500/10\">\n                    <div className=\"flex items-center justify-between mb-2\">\n                      <p className=\"text-sm font-semibold text-ink\">{assessment.title || 'Technical Assessment'}</p>\n                    </div>\n                    {assessment.start_time > 0 ? (\n                      <p className=\"text-xs text-ink/50 mb-3\">\n                        Scheduled on: <span className=\"font-medium text-ink\">\n                          {new Date(assessment.start_time * 1000).toLocaleString('en-IN')}\n                        </span>\n                      </p>\n                    ) : (\n                      <p className=\"text-xs text-ink/50 mb-3\">Pending schedule</p>\n                    )}\n                    {isLive ? (\n                      <Link href={`/candidate/test/${assessment.id}`} className=\"flex items-center justify-center gap-2 w-full py-2 bg-purple-500 text-white rounded-lg text-xs font-bold hover:bg-purple-600 transition-colors shadow-sm\">\n                        <Play size={14} />
<truncated 2442 bytes>

/* ---------- CHUNK ---------- */

"  const [applications, setApplications] = useState<Application[]>([]);\n  const [interviews, setInterviews] = useState<any[]>([]);\n  const [assessments, setAssessments] = useState<Record<number, any>>({});\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    async function load() {\n      try {\n        const [appsRes, intsRes] = await Promise.all([\n          moodleCall<{ applications: Application[] }>('local_aurahr_jobs_list_applications', { jobid: 0 }),\n          moodleCall<any[]>('local_aurahr_scheduler_get_interviews').catch(() => [])\n        ]);\n        \n        const apps = appsRes.applications || [];\n        setApplications(apps);\n        setInterviews(intsRes || []);\n\n        // Fetch assessments for any app in academia stage\n        const academiaApps = apps.filter(a => a.stage === 'academia');\n        const assessmentPromises = academiaApps.map(app => \n          moodleCall<any>('local_aurahr_jobs_get_assessment', { jobid: app.jobid })\n            .catch(() => null)\n        );\n        const assessmentResults = await Promise.all(assessmentPromises);\n        const assessmentMap: Record<number, any> = {};\n        academiaApps.forEach((app, idx) => {\n          if (assessmentResults[idx] && assessmentResults[idx].found) {\n            assessmentMap[app.jobid] = assessmentResults[idx];\n          }\n        });\n        setAssessments(assessmentMap);\n\n      } catch (err) {\n        console.error(err);\n      } finally {\n        setLoading(false);\n      }\n    }\n    load();\n  }, []);"

/* ---------- CHUNK ---------- */

"'use client';\n\nimport { useState, useEffect } from 'react';\nimport { motion } from 'framer-motion';\nimport { Calendar as CalendarIcon, Clock, ArrowRight, Video, Loader2, Check } from 'lucide-react';\nimport { moodleCall } from '@/lib/moodle';\n\nexport default function CandidateSchedulerPage() {\n  const [activeTab, setActiveTab] = useState<'interviews' | 'freetime'>('interviews');\n  const [interviews, setInterviews] = useState<any[]>([]);\n  const [availability, setAvailability] = useState<any[]>([]);\n  const [loading, setLoading] = useState(true);\n  const [saving, setSaving] = useState(false);\n\n  // Simple state for a weekly schedule (day 0 = Sunday)\n  const [schedule, setSchedule] = useState<Record<number, {start: string, end: string}>>({});\n\n  useEffect(() => {\n    async function loadData() {\n      try {\n        const [ints, avail] = await Promise.all([\n          moodleCall<any[]>('local_aurahr_scheduler_get_interviews').catch(() => []),\n          moodleCall<any[]>('local_aurahr_scheduler_get_availability').catch(() => [])\n        ]);\n        setInterviews(ints || []);\n        setAvailability(avail || []);\n\n        const initialSchedule: Record<number, {start: string, end: string}> = {};\n        (avail || []).forEach(slot => {\n          initialSchedule[slot.day_of_week] = {\n            start: `${slot.start_hour.toString().padStart(2, '0')}:${slot.start_min.toString().padStart(2, '0')}`,\n            end: `${slot.end_hour.toString().padStart(2, '0')}:${slot.end_min.toString().padStart(2, '0')}`\n          };\n        });\n        setSchedule(initialSchedule);\n      } catch (err) {\n        console.error(err);\n      } finally {\n        setLoading(false);\n      }\n    }\n    loadData();\n  }, []);\n\n  const handleRequestReschedule = async (id: number) => {\n    const reason = prompt('Please provide a reason for rescheduling:');\n    if (!reason) return;\n    try {\n      await moodleCall('local_aurahr_scheduler_request_reschedule', {\n        interviewid: id,\n        reason,\n    
<truncated 8387 bytes>

/* ---------- CHUNK ---------- */

"        <div className=\"grid grid-cols-2 md:grid-cols-5 gap-3 pt-5 border-t border-ink/5\">\n          <StatBox label=\"Total Applied\" value={total} />\n          <StatBox label=\"Academia Qual.\" value={qualifiedAcademia} />\n          <StatBox label=\"Interview Qual.\" value={qualifiedInterview} />\n          <StatBox label=\"Interviews Pending\" value={getCount('interview')} />\n          <StatBox label=\"Selected\" value={getCount('selected')} highlight />\n        </div>\n\n        <div className=\"mt-6 pt-5 border-t border-ink/5 flex items-center justify-between\">\n          <button \n            onClick={() => setShowAssessmentModal(true)}\n            className=\"flex items-center gap-2 px-4 py-2 bg-purple-500 text-white rounded-xl text-sm font-bold shadow-md hover:bg-purple-600 transition-colors\"\n          >\n            <GraduationCap size={16} /> Schedule Assessment\n          </button>\n        </div>\n      </div>\n\n      <AnimatePresence>\n        {showAssessmentModal && (\n          <AssessmentModal \n            jobId={jobId} \n            onClose={() => setShowAssessmentModal(false)} \n          />\n        )}\n      </AnimatePresence>"

/* ---------- CHUNK ---------- */

"function ScoreCard({ label, value, highlight }: { label: string; value: number; highlight?: boolean }) {\n  const pct = Math.min(100, Math.max(0, value));\n  return (\n    <div className={`p-3 rounded-xl ${highlight ? 'bg-sage/10 border border-sage/20' : 'bg-warm-sand/50'}`}>\n      <p className=\"text-[10px] text-ink/40 uppercase tracking-wider font-semibold\">{label}</p>\n      <p className={`text-lg font-bold font-mono mt-1 ${value > 0 ? (value >= 70 ? 'text-emerald-600' : 'text-amber-600') : 'text-ink/20'}`}>\n        {value > 0 ? `${value.toFixed(1)}%` : '—'}\n      </p>\n      {value > 0 && (\n        <div className=\"w-full h-1.5 bg-ink/5 rounded-full mt-2 overflow-hidden\">\n          <motion.div\n            initial={{ width: 0 }}\n            animate={{ width: `${pct}%` }}\n            transition={{ duration: 0.8, ease: 'easeOut' }}\n            className={`h-full rounded-full ${value >= 70 ? 'bg-emerald-500' : 'bg-amber-500'}`}\n          />\n        </div>\n      )}\n    </div>\n  );\n}\n\nfunction AssessmentModal({ jobId, onClose }: { jobId: number, onClose: () => void }) {\n  const [title, setTitle] = useState('');\n  const [date, setDate] = useState('');\n  const [time, setTime] = useState('');\n  const [duration, setDuration] = useState('60');\n  const [saving, setSaving] = useState(false);\n\n  const handleSubmit = async (e: React.FormEvent) => {\n    e.preventDefault();\n    setSaving(true);\n    try {\n      const dt = new Date(`${date}T${time}`);\n      const startTime = Math.floor(dt.getTime() / 1000);\n      await moodleCall('local_aurahr_jobs_schedule_assessment', {\n        jobid: jobId,\n        title,\n        start_time: startTime,\n        duration_mins: parseInt(duration, 10)\n      });\n      alert('Assessment scheduled successfully!');\n      onClose();\n    } catch (err) {\n      console.error(err);\n      alert('Failed to schedule assessment.');\n    } finally {\n      setSaving(false);\n    }\n  };\n\n  return (\n    <motion.div\n      initial={{ opacity: 0 }}\n      animate={
<truncated 2902 bytes>

/* ---------- CHUNK ---------- */

"  const handleFinalDecision = async (decision: string) => {\n    setUpdatingStage(true);\n    try {\n      let stage = '';\n      if (decision === 'select') stage = 'selected';\n      else if (decision === 'reject') stage = 'rejected';\n      else stage = 'interview'; // Hold keeps them in interview stage usually\n\n      await moodleCall('local_aurahr_jobs_submit_interview_result', {\n        applicationid: appId,\n        interview_score: parseFloat(score) || aiReport?.suggestedScore || 0,\n        recruiter_feedback: remarks,\n        ai_summary: aiReport?.report || '',\n        decision: stage\n      });\n      \n      alert(`Candidate marked as ${decision.toUpperCase()} and results saved.`);\n      router.push(`/org/applications/${appId}`); // Or wherever appropriate\n    } catch (err) {\n      console.error(err);\n      alert('Failed to update candidate status.');\n    } finally {\n      setUpdatingStage(false);\n    }\n  };"

/* ---------- CHUNK ---------- */

"  const handleSubmit = async (e: React.FormEvent) => {\n    e.preventDefault();\n    setSaving(true);\n    try {\n      const dt = new Date(`${date}T${time}`);\n      const startTime = Math.floor(dt.getTime() / 1000);\n\n      // Generate AI Assessment Questions\n      const aiRes = await fetch('/api/academia/generate', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ role: title, skills: 'React, Node, TypeScript' }) // In a real app we pass actual job skills here\n      });\n\n      if (!aiRes.ok) throw new Error('Failed to generate AI assessment');\n      \n      const aiData = await aiRes.json();\n      const questionsStr = JSON.stringify(aiData.questions || []);\n\n      await moodleCall('local_aurahr_jobs_schedule_assessment', {\n        jobid: jobId,\n        title,\n        questions: questionsStr,\n        num_questions: aiData.questions?.length || 5,\n        start_time: startTime,\n        duration_mins: parseInt(duration, 10)\n      });\n      alert('Assessment scheduled successfully with AI generated questions!');\n      onClose();\n    } catch (err) {\n      console.error(err);\n      alert('Failed to schedule assessment.');\n    } finally {\n      setSaving(false);\n    }\n  };"

/* ---------- CHUNK ---------- */

"  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState<string | null>(null);\n  const [selectedApp, setSelectedApp] = useState<ApplicationDetail | null>(null);\n  const [detailLoading, setDetailLoading] = useState(false);\n  const [editingDesc, setEditingDesc] = useState(false);\n  const [descText, setDescText] = useState('');\n  const [savingDesc, setSavingDesc] = useState(false);\n  const [showAssessmentModal, setShowAssessmentModal] = useState(false);\n\n  const loadApplications = useCallback(async () => {\n    if (!jobId) return;\n    setLoading(true);\n    setError(null);\n    try {\n      const [jobRes, appsRes] = await Promise.all([\n        moodleCall<Job>('local_aurahr_jobs_get_job', { jobid: jobId }),\n        moodleCall<{ applications: Application[]; total: number }>(\n          'local_aurahr_jobs_list_applications',\n          { jobid: jobId, stage: stageFilter, search, sort_field: sortField, sort_dir: sortDir }\n        ),\n      ]);\n      setJob(jobRes);\n      setDescText(jobRes.description || '');\n      setApplications(appsRes.applications);\n      setTotal(appsRes.total);\n    } catch (err: any) {\n      console.error('Failed to load:', err);\n      setError(err.message || 'Failed to load applications.');\n    } finally {\n      setLoading(false);\n    }\n  }, [jobId, stageFilter, search, sortField, sortDir]);\n\n  useEffect(() => { loadApplications(); }, [loadApplications]);"

/* ---------- CHUNK ---------- */

"  if (loading) {\n    return (\n      <div className=\"flex items-center justify-center h-64\">\n        <div className=\"w-8 h-8 border-2 border-sage/30 border-t-sage rounded-full animate-spin\" />\n      </div>\n    );\n  }\n\n  if (error || !job) {\n    return (\n      <div className=\"p-8 text-center text-rust bg-rust/5 rounded-xl border border-rust/10 max-w-2xl mx-auto mt-12\">\n        <h2 className=\"text-lg font-bold mb-2\">Error Loading Job</h2>\n        <p className=\"text-sm opacity-80\">{error || 'Job not found'}</p>\n        <button onClick={() => loadApplications()} className=\"mt-4 px-4 py-2 bg-rust text-white rounded-xl text-xs font-bold hover:bg-rust/90\">\n          Try Again\n        </button>\n      </div>\n    );\n  }\n\n  return (\n    <div className=\"space-y-6 max-w-7xl\">\n      {/* Header Card */}\n      <div className=\"bento-card p-6\">\n        <div className=\"flex items-start justify-between mb-4\">\n          <div>\n            <div className=\"flex items-center gap-3 mb-1\">\n              <h1 className=\"font-serif text-3xl font-bold text-ink tracking-tight\">\n                {job.title}\n              </h1>\n              <span className={`text-[10px] font-bold px-2 py-1 rounded-lg uppercase tracking-wider ${job.status === 'active' ? 'bg-emerald-500/15 text-emerald-700' : 'bg-ink/10 text-ink/50'}`}>\n                {job.status}\n              </span>\n            </div>\n            <div className=\"text-ink/50 text-xs flex items-center gap-4\">\n              <span><strong className=\"text-ink/70\">Created:</strong> {formatDate(job.timecreated)}</span>\n              <span><strong className=\"text-ink/70\">Finished (Deadline):</strong> {formatDate(job.deadline)}</span>\n            </div>\n          </div>\n          <div className=\"flex items-center gap-2\">\n            <button \n              onClick={() => setShowAssessmentModal(true)}\n              className=\"flex items-center gap-2 px-3 py-1.5 bg-purple-500/10 text-purple-600 rounded-xl text-xs font-bold hover:bg-pu
<truncated 2178 bytes>

/* ---------- CHUNK ---------- */

"              <input \n                type={showPassword ? 'text' : 'password'}\n                placeholder=\"Confirm New Password\"\n                className=\"input-field\"\n                value={passwords.confirm}\n                onChange={e => setPasswords({...passwords, confirm: e.target.value})}\n              />\n              <div className=\"pt-2\">\n                <button\n                  type=\"button\"\n                  onClick={handleChangePassword}\n                  disabled={savingPassword || !passwords.current || !passwords.new || !passwords.confirm}\n                  className=\"bg-blue-500 hover:bg-blue-600 text-white px-5 py-2.5 rounded-lg font-semibold text-sm transition-colors shadow-sm disabled:opacity-50\"\n                >\n                  {savingPassword ? 'Updating...' : 'Update Password'}\n                </button>\n              </div>\n            </div>\n          </div>"

/* ---------- CHUNK ---------- */

"  const [theme, setTheme] = useState('system');\n  const [saved, setSaved] = useState(false);\n  const [loading, setLoading] = useState(true);\n  const [saving, setSaving] = useState(false);\n  const [savingPassword, setSavingPassword] = useState(false);\n\n  useEffect(() => {\n    async function loadSettings() {\n      try {\n        const res = await moodleCall<any>('local_aurahr_jobs_get_user_prefs');\n        const data = JSON.parse(res.data || '{}');\n        if (data.notifs) setNotifs(data.notifs);\n        if (data.privacy) setPrivacy(data.privacy);\n        if (data.theme) setTheme(data.theme);\n      } catch (err) {\n        console.error('Failed to load settings', err);\n      } finally {\n        setLoading(false);\n      }\n    }\n    loadSettings();\n  }, []);\n\n  const handleChangePassword = async () => {\n    if (passwords.new !== passwords.confirm) {\n      alert('New passwords do not match!');\n      return;\n    }\n    setSavingPassword(true);\n    try {\n      await moodleCall('local_aurahr_jobs_change_password', {\n        currentpassword: passwords.current,\n        newpassword: passwords.new\n      });\n      alert('Password updated successfully!');\n      setPasswords({ current: '', new: '', confirm: '' });\n    } catch (err: any) {\n      console.error('Failed to update password', err);\n      alert(err.message || 'Failed to update password');\n    } finally {\n      setSavingPassword(false);\n    }\n  };\n\n  const handleSave = async (e: React.FormEvent) => {\n    e.preventDefault();\n    setSaving(true);\n    try {\n      await moodleCall('local_aurahr_jobs_update_user_prefs', {\n        data: JSON.stringify({ notifs, privacy, theme })\n      });\n\n      setSaved(true);\n      setTimeout(() => setSaved(false), 3000);\n    } catch (err: any) {\n      console.error('Failed to save settings', err);\n      alert(err.message || 'Failed to save settings');\n    } finally {\n      setSaving(false);\n    }\n  };"

/* ---------- CHUNK ---------- */

"  async function handleApply(jobId: number) {\n    setApplying(jobId);\n    try {\n      const applyRes = await moodleCall<{id: number, success: boolean}>('local_aurahr_jobs_apply', { jobid: jobId });\n      setApplied(prev => new Set(prev).add(jobId));\n      \n      if (applyRes && applyRes.id) {\n        // Fire and forget social profile analysis in the background\n        fetch('/api/socials/analyze', {\n          method: 'POST',\n          headers: { 'Content-Type': 'application/json' },\n          body: JSON.stringify({ applicationid: applyRes.id })\n        }).catch(err => console.error('Failed to trigger background analysis:', err));\n      }\n      \n    } catch (err: unknown) {\n      const msg = err instanceof Error ? err.message : 'Apply failed';\n      alert(msg);\n    } finally {\n      setApplying(null);\n    }\n  }"

/* ---------- CHUNK ---------- */

"  useEffect(() => {\n    if (!camStream) {\n      if (brightCheckRef.current) clearInterval(brightCheckRef.current);\n      setCamBrightness(null);\n      return;\n    }\n\n    let faceapiLoaded = false;\n    let detectorOptions: any = null;\n    let faceapi: any = null;\n\n    const initFaceApi = async () => {\n      if (typeof window !== 'undefined') {\n        faceapi = require('@vladmandic/face-api');\n        // Load tiny face detector model from unpkg/jsdelivr\n        await faceapi.nets.tinyFaceDetector.loadFromUri('https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model/');\n        detectorOptions = new faceapi.TinyFaceDetectorOptions();\n        faceapiLoaded = true;\n      }\n    };\n\n    initFaceApi().catch(console.error);\n\n    const startLoop = () => {\n      brightCheckRef.current = setInterval(async () => {\n        const vid = camVideoRef.current;\n        if (!vid || vid.readyState < 2) return;\n\n        // If the video element has no real dimensions, the stream isn't rendering\n        if (!vid.videoWidth || !vid.videoHeight) {\n          setCamBrightness(-1);\n          return;\n        }\n\n        // If faceapi is loaded, use real face detection\n        if (faceapiLoaded && detectorOptions && faceapi) {\n          try {\n            const detections = await faceapi.detectAllFaces(vid, detectorOptions);\n            if (detections && detections.length > 0) {\n              setCamBrightness(100); // 100 means \"face detected\" for the UI logic\n            } else {\n              setCamBrightness(-1); // -1 means \"no face detected\" or \"covered\"\n            }\n          } catch (e) {\n            console.error(\"Face detection error:\", e);\n            setCamBrightness(-1);\n          }\n        } else {\n          setCamBrightness(-1); // loading\n        }\n      }, 500);\n    };\n\n    const vid = camVideoRef.current;\n    if (vid && vid.readyState >= 3) {\n      setTimeout(startLoop, 1500); // warm-up\n    } else if (vid) {\n      vid.onplaying = () => setTimeout(startLoop, 1500)
<truncated 133 bytes>

/* ---------- CHUNK ---------- */

"  }, [camStream]);\n\n  // Automated microphone analysis\n  useEffect(() => {\n    if (!micStream) {\n      if (micCheckRef.current) cancelAnimationFrame(micCheckRef.current);\n      setMicVolume(0);\n      setMicPass(false);\n      return;\n    }\n\n    let audioContext: AudioContext | null = null;\n\n    try {\n      audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();\n      const analyser = audioContext.createAnalyser();\n      const source = audioContext.createMediaStreamSource(micStream);\n      \n      source.connect(analyser);\n      analyser.fftSize = 256;\n      const bufferLength = analyser.frequencyBinCount;\n      const dataArray = new Uint8Array(bufferLength);\n\n      const checkVolume = () => {\n        analyser.getByteFrequencyData(dataArray);\n        let sum = 0;\n        for (let i = 0; i < bufferLength; i++) sum += dataArray[i];\n        const average = sum / bufferLength;\n\n        setMicVolume(average);\n        \n        // Threshold for human speech / noise\n        if (average > 15) {\n          setMicPass(true);\n        }\n\n        micCheckRef.current = requestAnimationFrame(checkVolume);\n      };\n\n      checkVolume();\n    } catch (e) {\n      console.error('AudioContext error:', e);\n    }\n\n    return () => {\n      if (micCheckRef.current) cancelAnimationFrame(micCheckRef.current);\n      if (audioContext && audioContext.state !== 'closed') {\n        audioContext.close().catch(console.error);\n      }\n    };\n  }, [micStream]);\n\n  // ── Live proctoring ────────────────────────────────────────────────────"

/* ---------- CHUNK ---------- */

"  async function checkMic() {\n    setMicCheck({ status: 'checking' });\n    try {\n      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });\n      setMicStream(stream); // Opens mic preview modal\n      setMicCheck({ status: 'idle' });\n    } catch (err: any) {\n      setMicCheck({\n        status: 'fail',\n        error: err?.message?.includes('Permission')\n          ? 'Microphone permission denied.'\n          : 'Microphone not found or in use by another app.',\n      });\n    }\n  }\n\n  function confirmMic() {\n    if (micStream) {\n      micStream.getTracks().forEach(t => t.stop());\n      setMicStream(null);\n    }\n    setMicCheck({ status: 'ok' });\n  }\n\n  function rejectMic() {\n    if (micStream) {\n      micStream.getTracks().forEach(t => t.stop());\n      setMicStream(null);\n    }\n    setMicCheck({\n      status: 'fail',\n      error: 'Microphone check failed. Please ensure your microphone is unmuted and working.',\n    });\n  }"

/* ---------- CHUNK ---------- */

"      {/* ── Microphone Preview Modal ───────────────────────────────────────── */}\n      {micStream && (\n        <div className=\"fixed inset-0 z-[200] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4\">\n          <motion.div\n            initial={{ scale: 0.9, opacity: 0 }}\n            animate={{ scale: 1, opacity: 1 }}\n            className=\"bg-white rounded-3xl p-6 max-w-md w-full shadow-2xl\"\n          >\n            <h3 className=\"font-serif text-lg font-bold text-ink mb-1 text-center\">Microphone Check</h3>\n            <p className=\"text-sm text-ink/50 text-center mb-6\">\n              Please say something out loud to test your microphone.\n            </p>\n\n            {/* Volume indicator */}\n            <div className=\"bg-ink/5 rounded-full h-8 mb-6 overflow-hidden relative flex items-center px-2\">\n              <div\n                className={`absolute left-0 top-0 bottom-0 transition-all duration-75 ${micPass ? 'bg-emerald-400' : 'bg-blue-400'}`}\n                style={{ width: `${Math.min(100, micVolume * 2)}%` }}\n              />\n              <div className=\"z-10 w-full flex justify-between text-[10px] font-bold text-ink/40 uppercase\">\n                <span>Quiet</span>\n                <span>Loud</span>\n              </div>\n            </div>\n\n            {/* Status indicator */}\n            <div className={`mb-6 px-4 py-3 rounded-xl flex items-center gap-3 text-sm font-semibold\n              ${micPass ? 'bg-emerald-50 border border-emerald-200 text-emerald-700' : 'bg-amber-50 border border-amber-200 text-amber-700'}`}\n            >\n              {!micPass && <Loader2 size={16} className=\"animate-spin shrink-0\" />}\n              {micPass && <span className=\"text-lg\">✅</span>}\n              <span>\n                {micPass ? 'Audio detected! Microphone is working.' : 'Listening for audio...'}\n              </span>\n            </div>\n\n            <div cl
<truncated 854 bytes>

/* ---------- CHUNK ---------- */

"  // Automated microphone analysis\n  useEffect(() => {\n    if (!micStream) {\n      if (micCheckRef.current) cancelAnimationFrame(micCheckRef.current);\n      setMicVolume(0);\n      setMicPass(false);\n      return;\n    }\n\n    let audioContext: AudioContext | null = null;\n    let lastSpokeTime = 0;\n\n    const handleTrackEndOrMute = () => {\n      setMicPass(false);\n      lastSpokeTime = 0;\n    };\n\n    const audioTrack = micStream.getAudioTracks()[0];\n    if (audioTrack) {\n      audioTrack.addEventListener('ended', handleTrackEndOrMute);\n      audioTrack.addEventListener('mute', handleTrackEndOrMute);\n    }\n\n    try {\n      audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();\n      const analyser = audioContext.createAnalyser();\n      const source = audioContext.createMediaStreamSource(micStream);\n      \n      source.connect(analyser);\n      analyser.fftSize = 256;\n      const bufferLength = analyser.frequencyBinCount;\n      const dataArray = new Uint8Array(bufferLength);\n\n      const checkVolume = () => {\n        analyser.getByteFrequencyData(dataArray);\n        let sum = 0;\n        for (let i = 0; i < bufferLength; i++) sum += dataArray[i];\n        const average = sum / bufferLength;\n\n        setMicVolume(average);\n        \n        const now = Date.now();\n        // Threshold for human speech / noise\n        if (average > 15) {\n          setMicPass(true);\n          lastSpokeTime = now;\n        } else {\n          // If silence for 3 seconds, reset pass state\n          if (lastSpokeTime > 0 && (now - lastSpokeTime > 3000)) {\n            setMicPass(false);\n            lastSpokeTime = 0;\n          }\n        }\n\n        micCheckRef.current = requestAnimationFrame(checkVolume);\n      };\n\n      checkVolume();\n    } catch (e) {\n      console.error('AudioContext error:', e);\n    }\n\n    return () => {\n      if (micCheckRef.current) cancelAnimationFrame(micCheckRef.current);\n      if (audioContext && audioContext.state !== 'closed') {\
<truncated 266 bytes>

/* ---------- CHUNK ---------- */

"// Timer state for the assessment\n  const [timeLeft, setTimeLeft] = useState<number>(0);\n\n  // Helper to format seconds -> mm:ss\n  const formatTime = (seconds: number) => {\n    const m = String(Math.floor(seconds / 60)).padStart(2, '0');\n    const s = String(seconds % 60).padStart(2, '0');\n    return `${m}:${s}`;\n  };\n\n  // Initialize timer when assessment data is loaded\n  useEffect(() => {\n    if (assessment?.time_limit_seconds) {\n      setTimeLeft(assessment.time_limit_seconds);\n    } else {\n      // default 30 minutes if not specified\n      setTimeLeft(30 * 60);\n    }\n  }, [assessment]);\n\n  // Countdown effect\n  useEffect(() => {\n    if (timeLeft <= 0) return;\n    const id = setInterval(() => {\n      setTimeLeft(prev => {\n        if (prev <= 1) {\n          clearInterval(id);\n          // Auto‑submit when time expires\n          handleSubmit();\n          return 0;\n        }\n        return prev - 1;\n      });\n    }, 1000);\n    return () => clearInterval(id);\n  }, [timeLeft]);\n\n  // Show timer in the test UI (right after the top‑level wrapper)\n  const timerUI = (\n    <div className=\"text-xl font-bold text-ink mb-4 text-center\">\n      Time left: {formatTime(timeLeft)}\n    </div>\n  );\n\n"

/* ---------- CHUNK ---------- */

"  // ── Active test ────────────────────────────────────────────────────────\n  return (\n    <div className=\"fixed inset-0 bg-cream z-50 overflow-y-auto p-8 pt-12\">\n      <div className=\"max-w-4xl mx-auto flex gap-8\">\n\n        {/* Question nav + Timer */}\n        <div className=\"w-64 shrink-0\">\n          <div className=\"bento-card p-5 sticky top-6 space-y-4\">\n\n            {/* ── Countdown Timer ── */}\n            <div className={`flex items-center justify-center gap-2 px-4 py-3 rounded-2xl font-mono font-bold text-2xl\n              ${timeLeft <= 60\n                ? 'bg-red-100 text-red-600 animate-pulse'\n                : timeLeft <= 300\n                  ? 'bg-amber-50 text-amber-600'\n                  : 'bg-ink/5 text-ink'}`}>\n              <Clock size={18} className=\"shrink-0\" />\n              {formatTime(timeLeft)}\n            </div>\n\n            {violationCount > 0 && (\n"

/* ---------- CHUNK ---------- */

"  useEffect(() => {\n    if (!micStream) {\n      if (micCheckRef.current) clearTimeout(micCheckRef.current);\n      setMicVolume(0);\n      setMicPass(false);\n      return;\n    }\n\n    let audioContext: AudioContext | null = null;\n    let lastSpokeTime = 0;\n\n    const handleTrackEndOrMute = () => {\n      setMicPass(false);\n      lastSpokeTime = 0;\n    };\n\n    const audioTrack = micStream.getAudioTracks()[0];\n    if (audioTrack) {\n      audioTrack.addEventListener('ended', handleTrackEndOrMute);\n      audioTrack.addEventListener('mute', handleTrackEndOrMute);\n    }\n\n    try {\n      audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();\n      const analyser = audioContext.createAnalyser();\n      const source = audioContext.createMediaStreamSource(micStream);\n      \n      source.connect(analyser);\n      analyser.fftSize = 256;\n      const bufferLength = analyser.frequencyBinCount;\n      const dataArray = new Uint8Array(bufferLength);\n\n      const checkVolume = () => {\n        analyser.getByteFrequencyData(dataArray);\n        let sum = 0;\n        for (let i = 0; i < bufferLength; i++) sum += dataArray[i];\n        const average = sum / bufferLength;\n\n        // Only update state if it significantly changed, or just throttle to 10 FPS\n        setMicVolume(average);\n        \n        const now = Date.now();\n        // Threshold for human speech / noise\n        if (average > 15) {\n          setMicPass(true);\n          lastSpokeTime = now;\n          if (started && !completed && !isEndingRef.current && (now - lastAudioViolRef.current > 10000)) {\n             if (average > 40) { // louder threshold for violation\n                lastAudioViolRef.current = now;\n                setViolationCount(v => v + 1);\n                logViolation('loud_noise', 'Loud noise or voices detected');\n                alert('⚠️ VIOLATION: Loud noises or voices detected!');\n             }\n          }\n        } else {\n          // If silence for 3 seconds, reset pass
<truncated 799 bytes>

/* ---------- CHUNK ---------- */

"    let isActive = true;\n\n    const loopStep = async () => {\n      if (!isActive) return;\n      \n      const vid = camVideoRef.current;\n      if (!vid || vid.readyState < 2) {\n        if (isActive) brightCheckRef.current = window.setTimeout(loopStep, 500) as any;\n        return;\n      }\n\n      if (!vid.videoWidth || !vid.videoHeight) {\n        setCamBrightness(-1);\n        if (isActive) brightCheckRef.current = window.setTimeout(loopStep, 500) as any;\n        return;\n      }\n\n      if (faceapiLoaded && detectorOptions && faceapi) {\n        try {\n          const detections = await faceapi.detectAllFaces(vid, detectorOptions);\n          const numFaces = detections ? detections.length : 0;\n          if (numFaces > 0) {\n            setCamBrightness(100);\n          } else {\n            setCamBrightness(-1);\n          }\n\n          if (started && !completed && !isEndingRef.current) {\n            const now = Date.now();\n            if (numFaces === 0 && now - lastFaceViolRef.current > 10000) {\n              lastFaceViolRef.current = now;\n              setViolationCount(v => v + 1);\n              logViolation('no_face_detected', 'Candidate looking away or covered');\n              alert('⚠️ VIOLATION: Face not detected or looking away!\\nPlease look at the screen.');\n            } else if (numFaces > 1 && now - lastFaceViolRef.current > 10000) {\n              lastFaceViolRef.current = now;\n              setViolationCount(v => v + 1);\n              logViolation('multiple_faces', 'Multiple people detected');\n              alert('⚠️ VIOLATION: Multiple people detected in frame!');\n            }\n          }\n        } catch (e) {\n          console.error(\"Face detection error:\", e);\n          setCamBrightness(-1);\n        }\n      } else {\n        setCamBrightness(-1);\n      }\n\n      if (isActive) brightCheckRef.current = window.setTimeout(loopStep, 500) as any;\n    };\n\n    const deviceLoopStep = async () => {\n      if (!isActive) return;\n      \n      if (started &
<truncated 1472 bytes>

/* ---------- CHUNK ---------- */

"    const deviceCheckRef = { current: null as number | null };\n    let cocoModel: cocoSsd.ObjectDetection | null = null;\n    \n    const initCoco = async () => {\n      try {\n        await tf.ready();\n        cocoModel = await cocoSsd.load({ base: 'lite_mobilenet_v2' });\n      } catch (e) { console.error('Coco-SSD error:', e); }\n    };\n    initCoco();\n\n    const deviceLoopStep = async () => {\n      if (!isActive) return;\n      \n      if (started && !completed && !isEndingRef.current && cocoModel) {\n        const vid = camVideoRef.current;\n        if (vid && vid.readyState >= 2) {\n          try {\n            const predictions = await cocoModel.detect(vid);\n            const device = predictions.find(p => p.class === 'cell phone' || p.class === 'laptop' || p.class === 'remote');\n            if (device) {\n              const now = Date.now();\n              if (now - lastDeviceViolRef.current > 10000) {\n                lastDeviceViolRef.current = now;\n                setViolationCount(v => v + 1);\n                logViolation('device_detected', `Detected: ${device.class}`);\n                alert(`⚠️ VIOLATION: Unauthorized device (${device.class}) detected!`);\n              }\n            }\n          } catch (e) { /* ignore */ }\n        }\n      }\n      \n      if (isActive) deviceCheckRef.current = window.setTimeout(deviceLoopStep, 2000) as any;\n    };"

/* ---------- CHUNK ---------- */

"// ────────────────────────────────────────────────────────────────────────────\n\nfunction CheckButton({\n  label, status, error, icon: Icon, iconFail: IconFail, onClick,\n}: {\n  label: string; status: CheckStatus; error?: string;\n  icon: any; iconFail: any; onClick: () => void;\n}) {\n  const bg =\n    status === 'ok'       ? 'bg-emerald-50 border-emerald-300'   :\n    status === 'fail'     ? 'bg-red-50 border-red-300'           :\n    status === 'checking' ? 'bg-amber-50 border-amber-300'       :\n    'bg-white border-ink/10 hover:bg-ink/5';\n\n  const textColor =\n    status === 'ok'       ? 'text-emerald-700' :\n    status === 'fail'     ? 'text-red-600'     :\n    status === 'checking' ? 'text-amber-700'   : 'text-ink/60';\n\n  const IconComp = status === 'fail' ? IconFail : Icon;\n\n  return (\n    <button onClick={onClick} disabled={status === 'checking'}\n      className={`p-5 rounded-2xl border flex flex-col items-center gap-2 transition-all w-full ${bg}`}\n    >\n      {status === 'checking'\n        ? <Loader2 size={26} className=\"animate-spin text-amber-600\" />\n        : <IconComp size={26} className={textColor} />\n      }\n      <div className=\"font-semibold\">{label}</div>\n      {status === 'fail' && error && (\n        <div className=\"text-xs text-red-600 mt-2 text-center\">{error}</div>\n      )}\n    </button>\n  );\n}"

/* ---------- CHUNK ---------- */

"  async function handleSubmit() {\n    setSubmitting(true);\n    try {\n      // Backend not implemented yet, using mock\n      /*\n      const res = await moodleCall<any>('local_aurahr_academia_submit_test', {\n        assessmentid: assessment.id,\n        jobid:        jobId,\n        answers:      JSON.stringify(answers),\n        violations:   violationCount,\n      });\n      setFinalScore(res.score);\n      */\n      \n      // Calculate a fake score based on how many answers they provided\n      const answeredCount = Object.keys(answers).length;\n      const score = questions.length > 0 ? Math.round((answeredCount / questions.length) * 100) : 0;\n      setFinalScore(score);\n      \n    } catch (err: any) {\n      console.error(err);\n      alert('Error submitting test: ' + (err.message || err.name || String(err)));\n    } finally {\n      setSubmitting(false);\n      setCompleted(true);\n    }\n  }"